### PR TITLE
fix(channels): restore lark/feishu config constructors

### LINKED ISSUE #1991: [Bug]: cargo build --release --features channel-lark fails on v0.1.7 (and dev branch) — PR #1358 split broke LarkChannel
### Summary

`cargo build --release --features channel-lark` fails with 9 errors on both v0.1.7 and dev branch.

### Affected component

channel

### Severity

S1 - workflow blocked

## Root Cause
PR #1358 ("split lark and feishu providers") updated `src/channels/mod.rs` to call 
`LarkChannel::from_lark_config()` and `LarkChannel::from_feishu_config()`, and 
references `self.platform`, but `src/channels/lark.rs` still has the old struct 
without `platform` field and only exposes `from_config()`.

## Errors (truncated)
- `E0599: no function or associated item named "from_lark_config"`
- `E0599: no function or associated item named "from_feishu_config"` 
- `E0609: no field "platform" on type "&LarkChannel"` (×4)
- `E0308: mismatched types — expected "LarkPlatform", found "bool"`
- `E0425: cannot find value "mention_only" in this scope`

### Expected behavior

Successful compilation with Lark/Feishu channel support.

### Steps to reproduce

```bash
git checkout v0.1.7
cargo build --release --features channel-lark
```

### Impact

Affected users: Anyone trying to build ZeroClaw with Feishu/Lark channel support on v0.1.7 or dev branch
Frequency: always — 100% reproducible
Consequence: Cannot compile with --features channel-lark on v0.1.7 or dev. 
Workaround: v0.1.6 compiles successfully, but misses v0.1.7 features (prompt injection defense, Novita AI provider, etc.)

### Logs / stack traces

```text

```

### ZeroClaw version

v0.1.7

### Rust version

rustc 1.93.1

### Operating system

Ubuntu 24.04

### Regression?

Yes, it worked before

### Pre-flight checks

- [x] I reproduced this on the latest main branch or latest release.
- [x] I redacted secrets/tokens from logs.
- [x] I removed personal identifiers and replaced identity-specific data with neutral placeholders.

### PR DESCRIPTION
**Pull request by theonlyhennygod**
## Summary
Restore Lark/Feishu constructor wiring and platform state after split; unblocks channel-lark builds by reintroducing from_lark_config/from_feishu_config paths used in channel bootstrap.

## Validation
- \
- \ currently fails on existing unrelated mainline regressions outside this patch scope

Closes #1991

## Summary by CodeRabbit

* **Refactor**
  * Improved platform distinction between Lark and Feishu integrations with more explicit configuration handling, ensuring each platform's endpoints and behavior are properly initialized and maintained across different setup paths.

### CODE REVIEW

**Comment by theonlyhennygod** [comment]
Superseded by mainline channels fix in commit 7bea2b89 (restores Lark/Feishu constructor wiring and platform-aware paths). Closing this PR to avoid duplicate/conflicting edits.
