### ISSUE TITLE
[Bug]: WATI channel PR (#1472) introduces compile errors in gateway/mod.rs

### ISSUE THREAD

**Issue by mqyang56** [zeroclaw-labs/zeroclaw#1585]
## Summary

`src/gateway/mod.rs` fails to compile after #1472 (WATI WhatsApp Business API channel). Three distinct errors stem from the same root cause: `WatiVerifyQuery` uses the unqualified `Deserialize` derive macro instead of `serde::Deserialize`, causing a cascade of type failures.

## Affected component

`security/sandbox` → `runtime/daemon` (gateway)

## Severity

**S1 — workflow blocked**: the crate cannot be compiled; all gateway functionality is broken.

## Current behavior

`cargo build` fails with:

```
error: cannot find derive macro `Deserialize` in this scope
  --> src/gateway/mod.rs:1337:17

error: cannot find attribute `serde` in this scope
  --> src/gateway/mod.rs:1339:7

error[E0277]: the trait bound `fn(State<AppState>, Query<WatiVerifyQuery>) -> ...: Handler<_, _>` is not satisfied
  --> src/gateway/mod.rs:661:29

error[E0063]: missing field `wati` in initializer of `gateway::AppState`
  --> src/gateway/mod.rs:1624:21

error[E0063]: missing field `wati` in initializer of `gateway::AppState`
  --> src/gateway/mod.rs:2342:21
```

## Expected behavior

`cargo build` compiles successfully with the WATI channel integrated.

## Steps to reproduce

```bash
git clone https://github.com/zeroclaw-labs/zeroclaw
cd zeroclaw
cargo build
```

## Root cause

`WatiVerifyQuery` at line 1337 writes:

```rust
#[derive(Debug, Deserialize)]
pub struct WatiVerifyQuery { ... }
```

Every other struct in the same file uses the qualified form `serde::Deserialize`. The unqualified `Deserialize` is not in scope, so the derive fails. This cascades:

1. `WatiVerifyQuery` does not implement `serde::de::DeserializeOwned`
2. `Query<WatiVerifyQuery>` cannot be used as an axum extractor
3. `handle_wati_verify` no longer satisfies `Handler<_, _>`

Additionally, two test `AppState` initializers (lines 1624 and 2342) are missing the `wati` field added by #1472.

**Fix:** change `#[derive(Debug, Deserialize)]` to `#[derive(Debug, serde::Deserialize)]` (consistent with the rest of the file), and add `wati: None` to the two incomplete `AppState` initializers.

## Impact

- **Affected users**: all — the crate does not compile
- **Frequency**: always (100% reproducible)
- **Consequence**: complete build failure introduced by merging #1472 without stable-toolchain CI verification

## Logs / stack traces

See errors above. Full output visible when running `cargo build` on current `main`.

## ZeroClaw version

`v0.1.6` / `aa45c30`

## Rust version

`rustc 1.90.0 (1159e78c4 2025-09-14)`

## Operating system

macOS 25.2.0 — reproduces on any platform

## Regression?

Yes, introduced by #1472.

## Pre-flight checks

- [x] Reproduced on the latest main branch (`aa45c30`)
- [x] No secrets/tokens in logs
- [x] No personal identifiers

**Comment by chumyin** [comment]
Closing as internal-tracking mirror.

Canonical tracking remains in Linear: https://linear.app/zeroclawlabs/issue/RMN-32/bug-wati-channel-pr-1472-introduces-compile-errors-in-gatewaymodrs

Reason:
- Internal execution decomposition is now managed in Linear-only for this repository.
- GitHub Issues are reserved for explicitly requested public/external tracking.

**Comment by chumyin** [comment]
Resolved by merged PR #1603. The WATI compile blockers ( derive and  state initializers) are present on  and no longer reproducible.

**Comment by chumyin** [comment]
Reopening per maintainer direction: this issue should stay active until resolved by a merged PR and verified. I will continue implementation work instead of closing by planning status.

**Comment by chumyin** [comment]
Verified resolution by merged PR #1603 on dev: it includes the WATI compile-blocker fixes in gateway state/derive paths and the issue is no longer reproducible on current dev. Closing as completed-by-PR.

**Comment by chumyin** [comment]
Reopening for full follow-through. This issue was closed manually without a merged PR reference; I will continue implementation/validation until it is genuinely resolved.

**Comment by chumyin** [comment]
Closing with verified merged-PR evidence.

Resolution path:
- Implemented/validated in merged PR #1603 (base: `dev`, merge commit `d78a6712ef26022482cf1d690db0778133d60cd0`)
- `src/gateway/mod.rs` now has `#[derive(Debug, serde::Deserialize)]` for `WatiVerifyQuery`
- `AppState` initializers include `wati: None` where required

This issue was reopened during audit to enforce follow-through rules; it is now confirmed completed by merged code.
