### PR TITLE
feat(docs): add GitHub Pages deployment with mdBook

### PR DESCRIPTION
**Pull request by theonlyhennygod**
## Summary

- Adds a GitHub Actions workflow (`deploy-docs.yml`) to build and deploy the `docs/` directory to GitHub Pages using **mdBook**
- Adds `book.toml` configuration for mdBook with ZeroClaw branding, edit links, and navy theme
- Restructures `docs/SUMMARY.md` into proper mdBook format with nested chapters covering all doc sections (getting started, references, ops, security, hardware, contributing, maintainers)
- Adds `/book` to `.gitignore` for local mdBook builds

## How it works

- On push to `master` (when docs change) or manual dispatch, the workflow builds the docs with mdBook and deploys via `actions/deploy-pages`
- The site will be available at `https://zeroclaw-labs.github.io/zeroclaw/`

## After merging

You'll need to **enable GitHub Pages** in the repo settings:
1. Go to Settings > Pages
2. Under "Build and deployment", select **GitHub Actions** as the source
3. Trigger the workflow manually (or push a docs change) to deploy

## Test plan

- [x] Verified mdBook builds successfully locally with no errors
- [ ] After merging, verify GitHub Pages deployment succeeds
- [ ] Verify the site renders correctly at the Pages URL

### CODE REVIEW

**Comment by theonlyhennygod** [comment]
## CI/CD Failure Analysis

This PR is failing **Lint, Test, Build (all platforms), Docs Quality, Check (32-bit), and Verify Benchmarks Compile**.

### Root Causes

**1. Branch is out of sync with master — merge conflicts causing compilation errors:**
- `src/providers/mod.rs:1251` — Rust parse error: `"Kimi Code",` uses a comma instead of `|` in a match pattern. This looks like a bad merge.
- `src/providers/claude_code.rs:426` — `AtomicUsize` and `Ordering` are undeclared (missing `use` imports).
- `src/channels/mod.rs:10486` — field `debouncer` specified more than once (duplicate struct field from merge).
- `src/config/schema.rs:9274` and `src/providers/ollama.rs:1446,1455` — `std::env::set_var` calls require an `unsafe` block (Rust 1.93+ change).

**2. Docs Quality — `docs/SUMMARY.md` has 8 MD025 violations:**
- mdBook's `SUMMARY.md` uses multiple `#` top-level headings by design, but the docs linter flags them. You'll need to either adjust the headings to use `##` or configure the linter to exclude `SUMMARY.md`.

### What to do
1. **Rebase onto latest `master`** to resolve the compilation conflicts.
2. Fix the `SUMMARY.md` markdown issues — use `##` for section headings instead of `#`, or add `SUMMARY.md` to the docs quality gate exclusion list.
3. Re-push to trigger a fresh CI run.
