### ISSUE TITLE
[Bug]: crate fails to compile — invalid raw string literals in `leak_detector.rs`

### ISSUE THREAD

**Issue by mqyang56** [zeroclaw-labs/zeroclaw#1577]
## Summary

`src/security/leak_detector.rs` (introduced in #1433) does not compile. Five regex patterns use `r"..."` raw string literals containing a literal `"` inside the character class `['\"]*`, which immediately terminates the raw string and produces cascading parse errors.

## Affected component

`security/sandbox`

## Severity

**S1 — workflow blocked**: the crate cannot be compiled at all; every downstream feature is broken.

## Current behavior

`cargo build` (or `./bootstrap.sh`) fails with 4 errors:

```
error: prefix `key` is unknown
  --> src/security/leak_detector.rs:92:99

error: prefix `ID` is unknown
  --> src/security/leak_detector.rs:109:76

error: unknown start of token: \
  --> src/security/leak_detector.rs:110:68

error[E0762]: unterminated character literal
  --> src/security/leak_detector.rs:110:72
```

## Expected behavior

`cargo build` compiles successfully; the `LeakDetector` scans outbound content as intended.

## Steps to reproduce

```bash
git clone https://github.com/zeroclaw-labs/zeroclaw
cd zeroclaw
cargo build
```

## Impact

- **Affected users**: all — the crate does not compile on any platform or Rust version
- **Frequency**: always (100% reproducible)
- **Consequence**: complete build failure; `leak_detector`, prompt-injection defense, and outbound leak scanning are entirely unavailable

## Logs / stack traces

```
error: prefix `key` is unknown
  --> src/security/leak_detector.rs:92:99
   |
92 |                 (Regex::new(r"api[_-]?key[=:]\s*['\"]*[a-zA-Z0-9_-]{20,}").unwrap(), "Generic API key"),
   |                                                                                                   ^^^
   = note: prefixed identifiers and literals are reserved since Rust 2021

error[E0762]: unterminated character literal
   --> src/security/leak_detector.rs:110:72
```

Root cause: in Rust, `r"..."` raw strings treat the first `"` as the closing delimiter — `\"` does **not** escape it. The `"` inside `['\"]*` terminates the raw string early.

Affected lines: 92, 110, 127, 128, 129.

Fix: replace `r"..."` with `r#"..."#` and drop the spurious `\` prefix on the inner `"`.

## ZeroClaw version

`v0.1.6` / `aa45c30`

## Rust version

`rustc 1.90.0 (1159e78c4 2025-09-14)`

## Operating system

macOS 25.2.0 (Darwin) — reproduces on any platform

## Regression?

Yes, introduced by #1433 (`feat(security): Add prompt injection defense and leak detection`).

## Pre-flight checks

- [x] Reproduced on the latest main branch (`aa45c30`)
- [x] No secrets/tokens in logs
- [x] No personal identifiers; all placeholders are neutral/project-scoped

**Comment by chumyin** [comment]
Thanks for the report, and sorry for the build break.

Status update:
- The raw-string compile issue in `src/security/leak_detector.rs` is already fixed on `dev` (commit `2f29ec75`).
- Validation on current `dev` passes for release+lock build:
  - `cargo build --release --locked -q`

`#1583` was closed without merge, but the fix itself is already present in `dev`, so this issue can be closed as resolved.
