### PR TITLE
feat(plugins): scope plugin config per-alias and remove raw env access

### LINKED ISSUE #5919: plugins: zc_env_read allowlist — restrict plugin access to env vars
## Context

The `zc_env_read` host function exposed to WASM plugins (added in #5913 for Phase 2 D2) lets any plugin with the `env_read` permission call `std::env::var(name)` for any variable by name. A plugin granted `env_read` to read its own API key (e.g. `FAL_API_KEY`) can, with the same permission, read:

- `OPENAI_API_KEY`, `ANTHROPIC_API_KEY`, `AWS_SECRET_ACCESS_KEY`, `CARGO_REGISTRY_TOKEN`, `DATABASE_URL`
- Session cookies, SSH agent sockets, any other secret in the process environment

An `env_read` permission grant "I need my own API key" escalates to "read every secret in the process."

WASM plugins are third-party binaries. The permission grant in the manifest should describe *which* env vars the plugin can read, not just *that* it can read env vars.

Surfaced in PR #5913 review (advisory, not blocking).

## Target

Three candidate designs, not mutually exclusive:

1. **Per-plugin manifest allowlist** (preferred — most explicit):
   ```toml
   permissions = [\"env_read\"]
   env_read_vars = [\"FAL_API_KEY\"]
   ```
   Enforced in `handle_env_read`: if `var_name` not in the allowlist, return permission-denied.

2. **Namespace convention** (simplest):
   Plugins can only read variables with a prefix like `ZC_PLUGIN_<name>_*` or `ZC_PLUGIN_SHARED_*`. Users set `ZC_PLUGIN_IMAGE_GEN_FAL_API_KEY` instead of `FAL_API_KEY`. Host rejects anything outside the prefix.

3. **Host-provided key store indirection** (most robust, biggest scope):
   Plugins don't read env at all. Instead, the host exposes `zc_secret_get(handle)` where `handle` is pre-bound to a specific secret by the operator in `[plugins.<name>]` config. Plugins never see raw env var names.

Option 1 has the lowest scope-cost and the clearest migration story: existing manifests keep working (empty `env_read_vars` → deny-all if `env_read` permission is present), and plugins opt into specific names.

## Why it matters

- **Secret exfiltration** — a well-intentioned plugin can be modified by an attacker (pre-signature, or via a compromised build) to harvest every secret in the environment the moment it's installed.
- **Trust boundary alignment** — the manifest is the operator's trust contract. Right now it lies by omission: "env_read" reads like "reads its own config"; it actually means "reads any process-global secret."
- **Signature verification default is disabled** — until `signature_mode = strict` is the default (which it cannot reasonably be during bootstrap), the manifest is the operator's primary tool. It needs to be precise.

## Current state

- `zc_env_read` host function calls `std::env::var(&var_name)` unconditionally after checking the `env_read` permission bit.
- `PluginManifest` has no field for describing *which* env vars a plugin needs.
- ADR-003 §Threat model calls out this gap explicitly.
- The only plugin that exists so far (`image-gen-fal`) reads exactly one var (`FAL_API_KEY`), so retrofitting option 1 is trivial.

## Scope out

OAuth flows, secret rotation, encrypted secret storage — separate larger scope. This issue is just: bound the name space that `env_read` can read from.

---

Referenced from ADR-003. Parent RFC: #5574. Introduced by #5913.

### PR DESCRIPTION
**Pull request by singlerider**
## Summary

- **Base branch:** `master` (all contributions)
- **What changed and why:**
  - Plugins no longer read process environment variables. The `zc_env_read` host function and its `EnvRead` permission are removed, closing the cross-plugin and raw-env secret exfiltration paths that #5919 flagged.
  - Per-plugin config now lives in `[plugins.entries.<alias>]`, a secret-typed map keyed by plugin alias. Values encrypt at rest under the same adjacent `.secret_key` as every other secret and resolve through the existing schema-mirror override grammar, e.g. `ZEROCLAW_plugins__entries__<alias>__config__<key>=$FAL_KEY`.
  - A plugin receives only its own resolved section, injected into the `execute` input under the reserved `__config` key. No read-by-name host surface, no `std::env::var` fallback.
  - `PluginPermission::EnvRead` renamed to `ConfigRead` with a serde alias on the old `env_read` token so existing manifests keep parsing.
  - The four checked-in WASM example plugins are deleted; they were the only consumers of the env-read surface and are superseded by the WASM-only, capability-gated direction.
- **Scope boundary:** Does not add any new host function, does not change the WASM bridge transport, does not touch network egress controls (that is #5918). Does not implement nested/`n`-depth config trees; the per-plugin section is a flat secret string map.
- **Blast radius:** `zeroclaw-config` schema (new `entries` field on `PluginsConfig`), `zeroclaw-plugins` runtime + wasm_tool, `zeroclaw-runtime` tool assembly (resolves each plugin's section at load). Root workspace `exclude` dropped. Plugin-protocol and crate AGENTS docs.
- **Linked issue(s):** Closes #5919
- **Labels:** plugins, config, security, enhancement

## Validation Evidence (required)

```bash
cargo fmt --all -- --check
cargo clippy -p zeroclaw-config -p zeroclaw-plugins -p zeroclaw-runtime --all-targets -- -D warnings
cargo test -p zeroclaw-config -p zeroclaw-plugins
```

- **Commands run and tail output:**
  - `cargo fmt --all -- --check` -> clean (FMT_OK).
  - `cargo clippy ... -- -D warnings` -> `Finished`, exit 0, no warnings.
  - `cargo test -p zeroclaw-config -p zeroclaw-plugins` -> `943 passed; 0 failed`, `8 passed`, `90 passed`, `41 passed; 0 failed` including `plugin_entry_config_resolves_own_section_and_isolates_others`, `inject_config_adds_config_key`, `inject_config_empty_leaves_args_untouched`, `inject_config_rejects_non_object_args`.
- **Beyond CI:** Verified per-alias isolation (one plugin cannot see another's section), `__config` omitted when the section is empty, non-object args rejected. Confirmed no remaining `zc_env_read`/`EnvRead` references in crates and no build references to the deleted plugin trees (workspace, CI, install.sh, xtask, justfile).
- **Skipped:** Full-workspace `cargo test` not run locally this session; scoped to the affected crates plus the `plugins-wasm` build of `zeroclaw-runtime` (the call site touched by the SSOT review). The authoritative full-workspace bar is CI, which is green on this branch (run `27958411840`: Format, Lint, Test, Security, Docs Style, CI Required Gate all pass). `.po` translation catalogs and generated `docs/book/book/` output left to the translation/build workflow, not hand-edited.

- **SSOT review follow-up (head update):** the `plugin_config` snapshot flagged in review is the same `Arc<Config>` snapshot every tool in `all_tools_with_runtime` is built from. A daemon `config/reload` (RPC `ConfigReload` -> `reload_tx`) tears down and rebuilds the daemon iteration, so the agent and its tools are reconstructed from the new `Config`; plugin config is never hot-swapped into a live `WasmTool`. A `WasmTool`-level resolver would require `Arc<RwLock<Config>>`, which is not available at this layer and would make plugin tools uniquely diverge from the snapshot model of all 70+ other tools. The invariant is now documented at the call site and in the Compatibility/Rollback sections per the reviewer's documented-alternative path. `cargo fmt --all -- --check` clean; `cargo check -p zeroclaw-runtime --features plugins-wasm` clean.

## Security & Privacy Impact (required)

- New permissions, capabilities, or file system access scope? **No** (a permission is removed; `EnvRead` deleted).
- New external network calls? **No**
- Secrets / tokens / credentials handling changed? **Yes**: plugin secrets move from raw process env into the secret-typed config tree, encrypted at rest and scoped to the owning plugin. This narrows secret access; plugins can no longer read arbitrary env vars or other plugins' secrets.
- PII, real identities, or personal data in diff, tests, fixtures, or docs? **No**
- Risk and mitigation: removes the raw-env exfiltration surface entirely; remaining egress risk for a plugin holding a legitimate secret is bounded by #5918.

## Compatibility (required)

- Backward compatible? **No** (intentional breaking change)
- Config / env / CLI surface changed? **Yes**
- Upgrade steps: plugins relying on `env_read` must migrate. Move secrets from process env into `[plugins.entries.<alias>]` and read them from the `__config` field of the `execute` input instead of calling `zc_env_read`. Operators bridge ecosystem values per alias, e.g. `ZEROCLAW_plugins__entries__<alias>__config__api_key=$FAL_KEY`. Old `env_read` permission tokens still parse via serde alias but the capability is gone.
- **Config reload semantics:** plugin config is resolved from the `Arc<Config>` snapshot the whole tool set is built from, identical to every other tool in `all_tools_with_runtime`. There is no live `WasmTool`-level resolver, so a plugin does not pick up a `[plugins.entries.<alias>].config` edit (for example an API-key rotation) until the tool set is rebuilt. A daemon `config/reload` (or a restart) rebuilds the agent and its tools from the new `Config` and the new value takes effect; an in-flight tool already holding the snapshot does not hot-swap mid-session. This matches the snapshot model of all other tools and is documented at the call site.

## Rollback (required for `risk: medium` and `risk: high`)

- Fast rollback command/path: `git revert <sha>`
- Feature flags or config toggles: None. This is a deliberate security hardening, not a behavioral feature, so there is no runtime toggle; rollback is `git revert`.
- Observable failure symptoms: **immediate on the first plugin invocation after upgrade**, not deferred. A plugin that still expects raw env access fails to find its config; grep logs for plugin execute errors referencing missing config keys. After a `[plugins.entries.<alias>].config` change, the new value applies once the tool set is rebuilt (daemon `config/reload` or restart), not mid-session.

### CODE REVIEW

**Review by WareWolf-MoonWall — DISMISSED** [review]
# Review — PR #8137 `feat(plugins): scope plugin config per-alias and remove raw env access`

**Reviewer:** WareWolf-MoonWall  
**Head reviewed:** `c016f667be10dc7bcd0620ef25f0c58a5d8e1371`  
**Labels:** config, dependencies, docs, enhancement, risk: high, runtime, size: M  
**Verdict:** `--request-changes`

---

Security-hardening PR that removes the `zc_env_read` host function and routes plugin secrets through the per-alias config tree. The direction is correct and the crypto is sound. One absolute-rule SSOT violation in the runtime call site must be resolved before merge.

---

### 🔴 Blocking — SSOT violation: `plugin_config` cloned at tool-assembly time and stored in `WasmTool`

**AGENTS.md absolute rule:** No piece of state lives in two places. Source of truth for plugin config is `PluginsConfig.entries` under `Arc<RwLock<Config>>`. Caching a copy elsewhere is a duplicate-state violation.

In `crates/zeroclaw-runtime/src/tools/mod.rs`, `all_tools_with_runtime()`:

```rust
let plugin_config = config
    .plugins
    .entry_config(&manifest.name)
    .cloned()          // ← snapshot captured here
    .unwrap_or_default();
tool_arcs.push(Arc::new(zeroclaw_plugins::wasm_tool::WasmTool::from_wasm(
    wasm_path.to_path_buf(),
    manifest.permissions.clone(),
    manifest.name.clone(),
    manifest.description.clone().unwrap_or_default(),
    plugin_config,     // ← stored inside WasmTool
)));
```

`config` here is a snapshot of the live config at tool-assembly time. `.cloned()` produces an owned `HashMap<String, String>` that is then stored inside the `WasmTool` `Arc`. Every subsequent `call_execute()` will use that snapshot, not the live config. If an operator updates `[plugins.entries.<alias>].config` (e.g. rotates an API key) and triggers a config reload, `WasmTool` silently continues using the old value. The AGENTS.md anti-pattern list calls out exactly this class of bug as the reason for the rule ("operator edits the canonical location, the cached copy serves stale data, the agent silently misbehaves").

The correct pattern per AGENTS.md is a resolver closure:

```rust
// Source of truth: Arc<RwLock<Config>>
let config_arc = Arc::clone(&config_arc);
let alias = manifest.name.clone();
let resolve_config: Arc<dyn Fn() -> HashMap<String, String> + Send + Sync> =
    Arc::new(move || {
        config_arc
            .read()
            .plugins
            .entry_config(&alias)
            .cloned()
            .unwrap_or_default()
    });
// Pass the resolver, not the snapshot
WasmTool::from_wasm(..., resolve_config)
```

`call_execute()` would then call `(self.config_resolver)()` to resolve on each invocation. No cached copy, no drift.

If the runtime does not support hot-reload of plugin tools (requiring a daemon restart to pick up config changes), that invariant must be documented explicitly in the call site with a comment — and the Rollback and Compatibility sections must state that API-key rotation for plugins requires a restart. Under the current PR neither path is documented, leaving the behavior ambiguous.

---

### ✅ Resolved — All `std::env::var` calls removed from plugin paths

`handle_env_read()` and the `zc_env_read` host function are deleted in full from `crates/zeroclaw-plugins/src/runtime.rs`. No remaining `std::env::var` call appears in any plugin-facing execution path. The `PluginPermission::EnvRead` variant is renamed to `ConfigRead` with `#[serde(alias = "env_read")]` so existing manifests continue parsing without error. The docs in `plugin-protocol.md` are updated to match.

---

### ✅ Resolved — Per-alias isolation correct and tested

`inject_config()` is pure (no side effects, no live config access) and correctly:
1. Strips any caller-supplied `__config` key before injecting the canonical config (`inject_config_strips_caller_supplied_config_when_section_empty` test).
2. Omits `__config` entirely when the plugin has no config section (`inject_config_empty_leaves_args_untouched`).
3. Rejects non-object args with an error (`inject_config_rejects_non_object_args`).
4. Isolation test in `zeroclaw-config` (`plugin_entry_config_resolves_own_section_and_isolates_others`) confirms plugin A cannot read plugin B's section.

The anti-spoofing design (strip before inject, not after) is correct — a hostile caller cannot pre-populate `__config` to influence what the plugin reads.

---

### ✅ Resolved — Migration path documented

Compatibility section correctly states the breaking change and the exact upgrade path (`ZEROCLAW_plugins__entries__<alias>__config__<key>` env override grammar, existing `env_read` tokens parse via serde alias). This is sufficient for an intentional breaking change in an Experimental crate.

---

### 🟡 Warning — Validation evidence scoped to three crates for risk: high

The author explicitly skipped full-workspace `cargo test`. CI runs the full workspace test suite and all checks pass (run `27958411840`), which is the authoritative bar. No blocking issue. However, per project convention for `risk: high` PRs, the Validation Evidence section should cite the CI run number or provide the full-workspace output. Future PRs at this risk tier should lead with `cargo test --workspace` evidence.

---

### 🟡 Warning — No feature flag toggle for rollback

Rollback section states "None" for feature flags. For a `risk: high` PR removing a capability that existing deployments may depend on, the lack of a toggle means the only rollback is `git revert`. This is acceptable given the change is a deliberate security hardening (not a behavioral feature), but the Rollback section should explicitly note that the observable failure symptom (plugin fails to find config keys it previously read from env) will be immediate on first plugin invocation after upgrade, not deferred.

---

### 🟡 Warning — Sequencing conflict with #8144

PR #8144 removes the Extism runtime entirely and replaces it with wasmtime WIT. This PR modifies `crates/zeroclaw-plugins/src/runtime.rs` (the Extism bridge) and `zeroclaw-runtime/src/tools/mod.rs` (the tool assembly). If #8144 lands, this PR's changes to those files become irrelevant or conflicting. If this PR lands first, #8144's removal of the Extism bridge will need to carry forward the `inject_config` pattern into the new runtime.

The maintainer should decide the sequencing (or which PR supersedes which) before either lands. The `__config` injection pattern this PR introduces is architecturally correct and should survive into whatever runtime replaces Extism.

---

### 🟢 `inject_config` is pure, testable, and correct

The function takes `args_json: &[u8]` and `config: &HashMap<String, String>` — no live config access, no side effects. The four unit tests cover the full behavioral contract. This is the right design for a function that the SSOT fix will also benefit from (a resolver that passes the resolved map at call time will slot in cleanly).

---

### 🟢 `PluginEntryConfig` schema design is sound

`#[prefix = "plugins.entries"]`, `#[natural_key = "name"]`, `#[secret]` on `config: HashMap<String, String>` — correct use of the schema-mirror grammar. Values encrypt at rest under the adjacent `.secret_key`. The `entry_config()` lookup is O(n) over `entries` (fine for typical plugin counts), and it returns `&HashMap<String, String>` without cloning, making the call-site fix straightforward.

---

### 🟢 No AI attribution trailers

Commit message grep across both commits returned no matches. Clean.

---

### 🟢 CI fully green

All 18 jobs pass (run `27958411840`). Format, Lint, Test, Security, Docs Style, CI Required Gate all green.

**Comment by WareWolf-MoonWall** [comment]
@singlerider — maintainer direction needed: #8137 (per-alias plugin config hardening), #7928 (bheatwole, wasmtime/WIT host), and #8144 (JordanTheJet, wasmtime runtime replacement) are in a three-way collision on the plugin runtime. #8144 replaces the Extism runtime this PR is hardening; #7928 and #8144 both implement a wasmtime/WIT host. A direction decision is needed before any of these can land. The SSOT fix in this PR (removing raw env access) is valuable regardless of which host wins — worth preserving in whichever path lands.

**Comment by WareWolf-MoonWall** [comment]
@singlerider — milestone flag: this PR is currently assigned to v0.8.2, but a changes-requested review has been posted and the three-way collision with #7928 and #8144 means it cannot land until a plugin-runtime direction decision is made. v0.8.2 milestone assignment needs your review — this PR is not merge-ready for that milestone.

**Comment by singlerider** [comment]
Thanks @WareWolf-MoonWall, addressed in d6f1e49895 plus a PR-body update.

On the 🔴 blocker: I dug into the call site and the SSOT framing is right but the resolver pattern does not fit this layer. `all_tools_with_runtime` receives `config: Arc<Config>`, an immutable snapshot, not `Arc<RwLock<Config>>`. Every one of the 70+ tools built in that function is built from that same snapshot. There is no live `RwLock<Config>` reachable here to resolve against, so a `WasmTool`-level resolver closure would make plugin tools uniquely diverge from the snapshot model of all other tools rather than restore the single source of truth.

The reason the snapshot is correct by construction is the reload path: a config change goes through the daemon `config/reload` RPC, which fires `reload_tx` and tears down and rebuilds the daemon iteration. The agent and its full tool set are reconstructed from the new `Config` on that rebuild, so a rotated `[plugins.entries.<alias>].config` value is picked up. Plugin config is never hot-swapped into a live `WasmTool`; the owned map is the fresh snapshot for that build, not a second source of truth.

I took your documented-alternative path: the invariant is now stated in a terse why-comment at the call site (so a future maintainer does not re-introduce a resolver that breaks consistency with the rest of the tool set), and the Compatibility and Rollback sections now state the reload semantics explicitly: a `[plugins.entries.<alias>]` edit (e.g. API-key rotation) takes effect on the next tool-set rebuild via `config/reload` or restart, not mid-session.

On the 🟡 warnings:
- Validation Evidence now cites the green CI run (`27958411840`) as the authoritative full-workspace bar and adds the local `fmt`/`check --features plugins-wasm` for the touched call site.
- Rollback now states the failure symptom is immediate on first plugin invocation after upgrade (not deferred) and notes there is no feature toggle because this is a deliberate hardening, so rollback is `git revert`.
- Sequencing vs #8144: noted. I opened #8172 as the competing route to #8144 that keeps and hardens the current capability-gated runtime; the `__config` injection pattern here is architecturally correct and should carry forward into whatever runtime lands. Maintainer to decide sequencing.

No behavior change in this push; it is the call-site comment plus body documentation of the existing snapshot/reload invariant.

**Review by Audacity88 — DISMISSED** [review]
Thanks @singlerider. I reviewed the live PR state at d6f1e49895f2f47cd8ede56cacc5e5268001887c, the linked #5919 discussion, WareWolf-MoonWall's dismissed request-changes review and follow-up comments, the current config/plugin/runtime/docs diffs, and the public CI/check status. I did not run local Cargo for this review-only pass; I relied on the PR's reported validation, green public CI, and source review.

### ✅ Resolved — Caller-supplied `__config` spoofing is closed

The current head correctly strips any caller-provided `__config` key before host injection. The empty-section test proves a forged `__config` is removed when no canonical config exists, and the present-section test proves the host value overrides the caller value. That is the right shape for the reserved-key boundary.

### 🟢 What looks good — Raw process environment access is gone

The `zc_env_read` host function and its `std::env::var` path are removed from the plugin runtime. Plugins now receive only their own alias-scoped section through the execute input, and the schema places those values under the secret-typed config tree. That matches the #5919 design direction and avoids a second provider-literal env-var namespace.

### 🟢 What looks good — The SSOT snapshot invariant is documented

WareWolf-MoonWall's prior SSOT concern is addressed by documenting the snapshot/reload invariant at the tool assembly call site and in the PR body. Given `all_tools_with_runtime()` builds the whole tool set from one `Arc<Config>` snapshot and `config/reload` rebuilds the daemon iteration, plugin config following the same snapshot model as the other tools is a reasonable boundary.

### 🔴 Blocking — `config_read` is documented but not enforced

The direction is right, but the current implementation does not enforce the permission boundary it exposes. This is separate from the prior SSOT snapshot point above. `PluginPermission::ConfigRead` is still the manifest permission for this surface, with the old `env_read` token kept as a serde alias, and `plugin-protocol.md` now documents per-plugin `__config` as `Permission: config_read`.

In the runtime, though, config injection is unconditional. `all_tools_with_runtime()` resolves `[plugins.entries.<alias>].config` for every discovered plugin and passes the owned map into `WasmTool::from_wasm()`. `WasmTool` stores both `permissions` and `config`, but `execute()` only uses `permissions` when constructing the Extism plugin. It then clones `config` and calls `runtime::call_execute()`. `call_execute()` calls `inject_config(args_json, config)` without receiving or checking the manifest permissions, and `inject_config()` inserts `__config` whenever the map is non-empty.

That means a plugin whose manifest does not request `config_read` still receives its configured secrets if an operator has a `[plugins.entries.<alias>].config` section. The old raw-env host function is gone, but the manifest permission contract still says whether the plugin can read config; today that contract is not enforced.

Please make the permission model match the documented contract. The narrow fix is to inject the config section only when the manifest permissions contain `PluginPermission::ConfigRead` (including manifests that parse legacy `env_read` through the alias), and to add a regression test showing a plugin/config pair without `config_read` does not receive `__config`. If the intended model is instead "the presence of `[plugins.entries.<alias>].config` is itself the grant", then `ConfigRead` should be removed from the manifest permission surface and the docs should say that explicitly. Keeping the permission but ignoring it is the unsafe middle ground.

**Review by WareWolf-MoonWall — COMMENTED** [review]
# Review — PR #8137 `feat(plugins): scope plugin config per-alias and remove raw env access`

**Reviewer:** WareWolf-MoonWall
**Prior review:** Round 25 — `--request-changes` at `c016f667be10dc7bcd0620ef25f0c58a5d8e1371` (DISMISSED)
**Current head:** `d6f1e49895f2f47cd8ede56cacc5e5268001887c`
**Verdict:** `--comment`

**Governance note:** Audacity88 holds an active `CHANGES_REQUESTED` review at `d6f1e498` with
a 🔴 Blocking finding (`config_read` permission documented but not enforced). Per project
governance: never approve over another reviewer's active CHANGES_REQUESTED. This comment records
the disposition of my prior blocker and independently validates Audacity88's finding.

---

### ✅ Resolved — Prior SSOT blocker: snapshot invariant documented and justified

My Round 25 blocker required either a resolver closure (`Arc<dyn Fn() -> HashMap<...> + Send + Sync>`)
or explicit documentation of the snapshot invariant. The author chose the documentation path:

- The Compatibility section now states: "plugin config is resolved from the `Arc<Config>` snapshot
  the whole tool set is built from … A daemon `config/reload` (or a restart) rebuilds the agent
  and its tools from the new `Config` and the new value takes effect."
- The call site in `all_tools_with_runtime()` carries an inline comment documenting the invariant.
- The Audacity88 review independently confirms: "plugin config following the same snapshot model
  as the other tools is a reasonable boundary" given that `config/reload` tears down and rebuilds
  the full tool set.

The invariant is now visible, intentional, and consistent with how all 70+ other tools are built
from the same `Arc<Config>` snapshot. The documented-alternative path is satisfied. ✅

---

### ✅ Resolved — `zc_env_read` / `EnvRead` fully removed

`handle_env_read()` and the `zc_env_read` Extism host function are deleted from
`crates/zeroclaw-plugins/src/runtime.rs`. `PluginPermission::EnvRead` is renamed to `ConfigRead`
with `#[serde(alias = "env_read")]` for backwards-compatible manifest parsing. No remaining
`std::env::var` call in any plugin-facing execution path. Per-alias isolation test
(`plugin_entry_config_resolves_own_section_and_isolates_others`) and the four `inject_config`
unit tests all pass. ✅

---

### 🔴 Confirming Audacity88's Blocker — `config_read` permission is not enforced at injection

I have independently verified Audacity88's finding by reading the diff:

In `crates/zeroclaw-plugins/src/runtime.rs`, `call_execute()` calls `inject_config(args_json, config)`
unconditionally — it does not check whether the manifest's permission set includes
`PluginPermission::ConfigRead` before injecting `__config`. In `wasm_tool.rs`, `execute()` uses
`self.permissions` only when constructing the Extism plugin object; it then clones `self.config`
and passes it directly to `call_execute()` without a permission guard.

The result: a plugin whose WASM manifest does **not** declare `config_read` still receives its
operator-configured secrets if `[plugins.entries.<alias>].config` is non-empty. The documented
permission contract is violated.

Two valid resolutions exist (as Audacity88 states):

1. **Enforce the permission**: inject `__config` only when
   `self.permissions.contains(&PluginPermission::ConfigRead)`, and add a regression test showing
   a plugin/config pair without `config_read` receives no `__config`.
2. **Remove the permission surface**: if the model is "presence of config section = implicit grant",
   remove `ConfigRead` from the enum and update `plugin-protocol.md` accordingly.

Keeping the permission documented but unenforced is the unsafe middle ground — it creates a false
security guarantee that operators may rely on. The author should choose one of the two resolution
paths above. Audacity88's 🔴 is correct and blocking.

---

### 🟡 Pending — Sequencing conflict with #8144 (Extism → wasmtime WIT)

My Round 25 warning about the sequencing conflict with #8144 stands. If #8144 lands first,
the `inject_config` pattern must be carried forward into the new runtime. If this PR lands first,
#8144's removal of the Extism bridge will need to preserve the `__config` injection contract
(and, once the permission enforcement fix lands, the permission guard). The maintainer should
confirm sequencing before either merges.

---

### Summary

Waiting on author to resolve Audacity88's active `CHANGES_REQUESTED` before this can be cleared.
The SSOT snapshot concern from my prior review is resolved. The `config_read` enforcement gap
is the sole remaining blocker; it belongs to Audacity88's active review.

**Review by Audacity88 — APPROVED** [review]
Thanks @singlerider. I reviewed head `8d78aba2a417915658c4b3221872b50e6628878b` against my prior `CHANGES_REQUESTED` review, your follow-up commit, @WareWolf-MoonWall's prior SSOT review/comment, the linked #5919 discussion, the current plugin runtime/tool assembly/docs diff, and the current public CI state. I did not run local Cargo for this review-only pass; I relied on source review, the PR's reported validation, and public CI/check status.

### ✅ Resolved — `config_read` now gates `__config` injection

The blocker from my prior review is resolved. `WasmTool::execute` now passes the manifest permissions into `runtime::call_execute`, and `call_execute` routes the configured map through `effective_config` before calling `inject_config`. Permissionless plugins receive an empty effective map, while plugins with `PluginPermission::ConfigRead` receive their resolved section.

The reserved-key behavior is preserved too. The empty map still goes through `inject_config`, so a caller-provided `__config` is stripped even when the plugin lacks `config_read`. The new regressions cover both sides: no `__config` for a plugin without `ConfigRead` even with a forged caller value, and config passed through when `ConfigRead` is present.

### ✅ Resolved — The prior SSOT and raw-env concerns remain clear

I re-checked the surrounding security shape on the current head. The raw `zc_env_read` host function and `std::env::var` path are still gone from the plugin runtime, the old `env_read` token still parses as `ConfigRead`, and the plugin-protocol docs now describe `config_read` as the permission for receiving `__config`.

@WareWolf-MoonWall's earlier SSOT concern also remains addressed by the documented snapshot/reload invariant at `all_tools_with_runtime()`: plugin config follows the same `Arc<Config>` snapshot model as the rest of the tool set, and a daemon `config/reload`/restart rebuilds tools from the new config.

### 🟡 Warning — This is code-review clearance, not merge readiness

I do not have a remaining code blocker on this head, but the current-head CI run was still in progress when I reviewed, and the plugin-runtime sequencing question with #8144/#7928/#8172 still needs maintainer ordering before merge. This approval clears my prior `config_read` blocker; it should not be read as a merge-ready call until the current checks finish green and maintainers settle the runtime sequencing.
