### PR TITLE
fix(channels): add missing ChannelMessage fields in orchestrator test

### PR DESCRIPTION
**Pull request by JordanTheJet**
## Summary

- **Base branch:** `master`
- **What changed and why:**
  - `master` currently fails the **Test** and **Lint** CI jobs for every PR that recompiles it. Root cause is a semantic merge collision between two PRs that each passed CI in isolation:
    - **#8389** (`feat(channels): add passive WhatsApp group context`) added two **required** fields to `ChannelMessage`: `passive_context` and `conversation_scope`.
    - **#8468** (`fix(channels): preserve image bytes for a configured vision_model_provider`) added a test that constructs `ChannelMessage { .. }` listing every field **explicitly** — written before #8389, so it omits the two new fields.
  - Together on `master` the test no longer compiles:
    ```
    error[E0063]: missing fields `conversation_scope` and `passive_context`
      in initializer of `zeroclaw_api::channel::ChannelMessage`
      --> crates/zeroclaw-channels/src/orchestrator/mod.rs:21190
    ```
  - The regular `Check`/`Build` jobs don't compile `#[cfg(test)]` code, which is why the break passed the per-PR checks and landed on `master` — only `Test` (`cargo test --no-run`) and `Lint` (`clippy --all-targets`) build the test target.
  - Fix: add `..Default::default()` to that one constructor so the two new fields default to `false` / `Sender`, matching how the crate's other `ChannelMessage` literals already supply them. One line, test-only.
- **Scope boundary:** Touches a single test constructor in `crates/zeroclaw-channels/src/orchestrator/mod.rs`. No production code, no behavior change.
- **Blast radius:** Restores compilation of the `zeroclaw-channels` test target; unblocks `Test`/`Lint` for all open PRs. Nothing else.
- **Linked issue(s):** None. Unblocks CI on `master` (regression from #8389 × #8468).
- **Labels:** `bug`, `channel`, `risk:low`, `size:XS`

## Validation Evidence (required)

- **Commands run and tail output:**

```
$ cargo test -p zeroclaw-channels --no-run --locked
   Compiling zeroclaw-channels v0.8.2
    Finished `test` profile [unoptimized + debuginfo] target(s) in 1m 13s   # previously: error[E0063]

$ cargo test -p zeroclaw-channels --lib media_pipeline_preserves_image_bytes_when_vision_route_configured
running 1 test
test orchestrator::tests::media_pipeline_preserves_image_bytes_when_vision_route_configured ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1137 filtered out

$ cargo clippy -p zeroclaw-channels --all-targets -- -D warnings
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 2m 43s   # no warnings

$ cargo fmt --all -- --check
FMT_OK (no diff)
```

Toolchain: `rustc 1.93.1 (01f6ddf75 2026-02-11)`. Branch is a single commit on current `master`.

- **Beyond CI — what did you manually verify?** Confirmed the failure reproduces on a clean `master` checkout, that this is the only constructor missing the fields (the test target now compiles to completion — the compiler had stopped at the first error), and that the previously-uncompilable test now passes at runtime. The added defaults (`passive_context: false`, `conversation_scope: Sender`) match the struct's `#[derive(Default)]` and the pre-#8389 behavior, so the test's intent is unchanged.
- **If any command was intentionally skipped, why:** Full-workspace `cargo test` not run end-to-end; the regression and fix are confined to one `zeroclaw-channels` test target, validated directly above.

## Security & Privacy Impact (required)

- New permissions, capabilities, or file system access scope? **No**
- New external network calls? **No**
- Secrets / tokens / credentials handling changed? **No**
- PII, real identities, or personal data in diff, tests, fixtures, or docs? **No**

## Compatibility (required)

- Backward compatible? **Yes** — test-only, no API or behavior change.
- Config / env / CLI surface changed? **No**

## Rollback (required for medium/high-risk PRs)

Low-risk: `git revert <sha>` (single one-line commit).

### CODE REVIEW

**Review by Audacity88 — APPROVED** [review]
Reviewed PR #8511 at head `be80059` against the live PR state, the one-line diff, related merged PRs #8389 and #8468, current checks, public source context for `ChannelMessage` defaults, and the lack of prior reviews/comments.

### 🟢 What looks good — Root cause is precisely diagnosed

This is the right minimal fix for the master CI break. The failure is a semantic merge collision between #8389, which added the required `passive_context` and `conversation_scope` fields to `ChannelMessage`, and #8468, which added a test with explicit field enumeration before those fields existed. Each PR compiled alone; together the test target breaks with `error[E0063]: missing fields`.

### 🟢 What looks good — Fix is minimal and correct

Adding `..Default::default()` fills `passive_context: false` and `conversation_scope: Sender` from the public `ChannelMessage` defaults. That matches the pre-#8389 behavior, keeps the test intent unchanged, and does not touch production code.

### 🟢 What looks good — CI validates the failing path

`Lint`, `Test`, and `CI Required Gate` are green on this head. The PR body also includes focused `zeroclaw-channels` validation for the compile failure and the affected test.

Approved.

**Review by singlerider — APPROVED** [review]
I traced this against upstream source and the two colliding PRs. The diagnosis and the fix both hold up.

### 🟢 What looks good — correct root cause, idiomatic fix

The break is exactly as described: #8389 added two required fields (`passive_context`, `conversation_scope`) to `ChannelMessage`, and #8468 landed a test constructing the struct with every field spelled out explicitly, written before #8389. The `Check`/`Build` jobs don't compile `#[cfg(test)]` code, so each PR passed in isolation and the collision only surfaces in `Test`/`Lint` on master. `..Default::default()` is the right fix here, not the spelled-out alternative: `ChannelMessage` derives `Default`, `passive_context: bool` defaults to `false`, and `ChannelConversationScope` has `#[default] Sender` (channel.rs:38-42), so the defaults resolve to exactly the pre-#8389 behavior and the test's intent is unchanged. It's also resilient to future required-field additions on the struct, where the explicit form would break again. Validation shows the test target compiling and the target test passing.

### 🟢 What looks good — test-only, zero blast radius

One line in one test constructor, no production code, no behavior change. This unblocks `Test`/`Lint` for every open PR that recompiles master, which is the right thing to prioritize landing.

One cross-reference for awareness: #8508 (open) carries the same constructor fix spelled out explicitly at this exact line. This PR is the cleaner fix and should land first to unblock CI; #8508 will then need a trivial merge resolution at orchestrator/mod.rs:21204. Not a blocker on this PR.

LGTM.
