### PR TITLE
fix(security): use r#"..."# raw strings in leak_detector regex patterns

### LINKED ISSUE #1577: [Bug]: crate fails to compile — invalid raw string literals in `leak_detector.rs`
## Summary

`src/security/leak_detector.rs` (introduced in #1433) does not compile. Five regex patterns use `r"..."` raw string literals containing a literal `"` inside the character class `['\"]*`, which immediately terminates the raw string and produces cascading parse errors.

## Affected component

`security/sandbox`

## Severity

**S1 — workflow blocked**: the crate cannot be compiled at all; every downstream feature is broken.

## Current behavior

`cargo build` (or `./bootstrap.sh`) fails with 4 errors:

```
error: prefix `key` is unknown
  --> src/security/leak_detector.rs:92:99

error: prefix `ID` is unknown
  --> src/security/leak_detector.rs:109:76

error: unknown start of token: \
  --> src/security/leak_detector.rs:110:68

error[E0762]: unterminated character literal
  --> src/security/leak_detector.rs:110:72
```

## Expected behavior

`cargo build` compiles successfully; the `LeakDetector` scans outbound content as intended.

## Steps to reproduce

```bash
git clone https://github.com/zeroclaw-labs/zeroclaw
cd zeroclaw
cargo build
```

## Impact

- **Affected users**: all — the crate does not compile on any platform or Rust version
- **Frequency**: always (100% reproducible)
- **Consequence**: complete build failure; `leak_detector`, prompt-injection defense, and outbound leak scanning are entirely unavailable

## Logs / stack traces

```
error: prefix `key` is unknown
  --> src/security/leak_detector.rs:92:99
   |
92 |                 (Regex::new(r"api[_-]?key[=:]\s*['\"]*[a-zA-Z0-9_-]{20,}").unwrap(), "Generic API key"),
   |                                                                                                   ^^^
   = note: prefixed identifiers and literals are reserved since Rust 2021

error[E0762]: unterminated character literal
   --> src/security/leak_detector.rs:110:72
```

Root cause: in Rust, `r"..."` raw strings treat the first `"` as the closing delimiter — `\"` does **not** escape it. The `"` inside `['\"]*` terminates the raw string early.

Affected lines: 92, 110, 127, 128, 129.

Fix: replace `r"..."` with `r#"..."#` and drop the spurious `\` prefix on the inner `"`.

## ZeroClaw version

`v0.1.6` / `aa45c30`

## Rust version

`rustc 1.90.0 (1159e78c4 2025-09-14)`

## Operating system

macOS 25.2.0 (Darwin) — reproduces on any platform

## Regression?

Yes, introduced by #1433 (`feat(security): Add prompt injection defense and leak detection`).

## Pre-flight checks

- [x] Reproduced on the latest main branch (`aa45c30`)
- [x] No secrets/tokens in logs
- [x] No personal identifiers; all placeholders are neutral/project-scoped

### PR DESCRIPTION
**Pull request by mqyang56**
Closes #1577.

## Problem

Five regex patterns in `src/security/leak_detector.rs` (introduced in #1433) used `r"..."` raw string literals containing a `"` inside the character class `['\"]*`. In Rust, raw strings treat the first `"` as the closing delimiter — `\"` does **not** escape it — so the string terminated early, producing four cascading parse errors and making the crate uncompilable.

## Change

Replace `r"..."` with `r#"..."#` for the five affected lines (92, 110, 127, 128, 129) and remove the redundant `\` before the inner `"`. Regex semantics are identical.

## Non-goals

Does not touch other pre-existing compile errors (WATI gateway issues from #1472, `floor_char_boundary` unstable API calls) — separate concerns.

## Risk and Rollback

**Low risk.** Single-file, purely syntactic correction, no behavior change.
Rollback: revert this commit.

## Validation

The four original `leak_detector.rs` compile errors are resolved after this change. Full `cargo build` is still blocked by unrelated pre-existing errors in other modules.

## Summary by CodeRabbit

* **Refactor**
  * Improved internal code quality in security detection patterns. No impact on detection behavior or security functionality.

### CODE REVIEW

**Comment by chumyin** [comment]
Closed after conflict analysis: the raw-string regex conversions in this PR are already present on current dev, so there is no independent change left to merge.
