### ISSUE TITLE
[Bug]: voice-wake feature fails to compile in v0.6.9

### ISSUE THREAD

**Issue by TTimo** [zeroclaw-labs/zeroclaw#5861]
### Affected component

runtime/daemon

### Severity

S1 - workflow blocked

## Environment

- zeroclaw: 0.6.9
- rustc: 1.94.1 (Arch Linux rust 1:1.94.1-1)
- cpal: 0.15.3 (from Cargo.lock)
- OS: Arch Linux
- Build command: `cargo build --release --frozen --features "...,voice-wake,..."`

## Errors

error[E0308]: mismatched types
   --> src/channels/voice_wake.rs:100:27
    |
    |             sample_rate = supported.sample_rate();
    |                           ^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `SampleRate`

error[E0560]: struct `ChannelMessage` has no field named `observe_group`
   --> src/channels/voice_wake.rs:242:41
    |
    |                                         observe_group: false,
    |                                         ^^^^^^^^^^^^^ `ChannelMessage` does not have this field

error[E0599]: no method named `secret_fields` found for reference `&VoiceWakeConfig` in the current scope
   --> src/config/schema.rs:6373:60
    | (+ 10 further E0599 errors for: `encrypt_secrets`, `decrypt_secrets`, `set_secret`,
    |    `prop_fields`, `get_prop`, `set_prop`, `prop_is_secret`, `configurable_prefix`,
    |    `init_defaults` — all on `VoiceWakeConfig`)

error: could not compile `zeroclawlabs` (lib) due to 13 previous errors

### Expected behavior

AUR package builds

### Steps to reproduce

```bash
Build Arch AUR package https://aur.archlinux.org/packages/zeroclaw
```

### Impact

Impacts .. me! And other Arch users.

### Logs / stack traces

```text

```

### ZeroClaw version

0.6.9

### Rust version

1.94.1 (Arch Linux rust 1:1.94.1-1)

### Operating system

Arch Linux

### Regression?

Yes, it worked before

### Pre-flight checks

- [ ] I reproduced this on the latest master branch or latest release.
- [x] I redacted secrets, tokens, and personal data from all submitted content.

**Comment by TTimo** [comment]
This problem doesn't happen out of main (`0.7.0.r2970.g0f8bd00`).

**Comment by singlerider** [comment]
Closing — @TTimo confirmed this does not reproduce on main (`0.7.0.r2970.g0f8bd00`). Specific to v0.6.9. Significant work has landed since this was filed. If still present on the latest `master`, please open a new issue with version info and ping @singlerider directly.
