### PR TITLE
fix(memory): wrap SqliteMemory embedder in Arc + flush before assert in log reinit test

### PR DESCRIPTION
**Pull request by singlerider**
### Context

During the stale-PR sweep this morning, #8623 (add embedding identity + auto-migrate) and #8359-era changes (hot-swap embedder without daemon restart) both landed on master. Additionally, #8439 (move JSONL fsync off the async hot path) landed. Each PR was green in isolation. The combined state has two problems:

**1. SqliteMemory does not compile:**

```
error[E0277]: the trait bound `RwLock<RawRwLock, Arc<dyn EmbeddingProvider>>: Clone` is not satisfied
  --> crates/zeroclaw-memory/src/sqlite.rs:54:5
   |
46 | #[derive(Clone)]
   |          -----
...
54 |     embedder: RwLock<Arc<dyn EmbeddingProvider>>,
```

`parking_lot::RwLock` is not `Clone`. #8623 added `#[derive(Clone)]`. #8359's hot-swap change had put `embedder` behind a bare `RwLock`. Neither CI run saw the other.

**2. `writer::tests::reinit_applies_changed_rotation_policy` races the async flush:**

```
thread 'writer::tests::reinit_applies_changed_rotation_policy' panicked at crates/zeroclaw-log/src/writer.rs:865:9:
assertion `left == right` failed
  left: 0
 right: 1
```

The test asserts `total_events(&path) == 1` immediately after `emit(\"before-reload\")`. Prior to #8439 the fsync was synchronous. #8439 moved it to a background worker, so the file has zero events by the time the assertion runs. Every other test that observes on-disk state after `emit()` already calls `flush_for_test()` for exactly this reason.

### Fix

**SqliteMemory:** wrap the `RwLock` in an `Arc`:

```rust
- embedder: RwLock<Arc<dyn EmbeddingProvider>>,
+ embedder: Arc<RwLock<Arc<dyn EmbeddingProvider>>>,
```

That makes the field `Clone`, keeps every `self.embedder.read()` / `.write()` call site identical via `Deref`, and matches what the type's doc comment already promised: \"all shared state is behind `Arc`\".

**Log reinit test:** add `flush_for_test().unwrap()` before each assertion, matching the pattern used by every other test in the same file.

### Validation

- `cargo check --workspace` passes clean
- `cargo test -p zeroclaw-log --lib writer::tests::reinit_applies_changed_rotation_policy` passes

### Risk

Low. The Arc wrap is a lock-sharing change that matches the field's stated intent. The test fix aligns one outlier test with the existing pattern used across the same file.

### CODE REVIEW

**Comment by singlerider** [comment]
@JordanTheJet — fast-lane review request. Master currently does not compile because two PRs landed back-to-back during the stale-PR sweep (#8623 + the earlier hot-swap-embedder change), and one log test races the new async fsync from #8439. This PR is the minimal fix for both:

- Wrap `SqliteMemory.embedder` `RwLock` in an `Arc` so `#[derive(Clone)]` compiles again. Zero behavior change — the type's own doc comment already claimed "all shared state is behind `Arc`".
- Add `flush_for_test()` calls before the two log-writer reinit tests that observe on-disk state. Every other test in the same file already does this; these two just predate #8439.

CI is green. Please review + merge when you get a moment so master is buildable again for everyone else.

**Review by WareWolf-MoonWall — APPROVED** [review]
Reviewed diff at 13c8748d. Fixes two post-merge integration failures introduced by concurrent landings: `SqliteMemory` non-`Clone` embedder and log-reinit test assertion races.

### 🟢 What looks good — `SqliteMemory` Arc wrap

`RwLock<Arc<dyn EmbeddingProvider>>` → `Arc<RwLock<Arc<dyn EmbeddingProvider>>>`: the outer `Arc` makes `SqliteMemory` `Clone` without requiring `EmbeddingProvider: Clone`. This follows the established pattern for hot-swappable providers in this codebase — the `RwLock` already correctly prevents races; the `Arc` just lets the handle be cloned cheaply.

### 🟢 What looks good — flush guards in reinit tests

The `flush_for_test().unwrap()` calls added before assertions in `reinit_applies_changed_rotation_policy` and `reinit_can_disable_persistence_without_restart` drain the async writer queue before the test checks on-disk state. The intermittent CI failures these tests caused were pure timing issues; the fix is minimal and correct.

Both fixes are tightly scoped to the immediate post-merge breakage. No new fields, no behavioral changes.

**Comment by Audacity88** [comment]
@singlerider thanks for pulling these two master breakages together quickly. I checked PR #8867 head `13c8748d` against current `master`, the merged split follow-ups #8868 and #8869, and the current-master-vs-#8867 diff for the touched files.

Current `master` now has the two fixes from this PR through those split follow-ups: #8868 landed the `SqliteMemory` shared embedder lock fix, and #8869 landed the log-writer reinit/flush fix.

#8867 is now `DIRTY` against `master`, and replaying this branch would drop the newer #8869 writer-shutdown lifecycle changes. I’m closing this PR as superseded by #8868 and #8869 so the queue reflects the code that actually landed.
