### ISSUE TITLE
[Bug]: channel-lark feature fails to compile on Windows (v0.1.7 and main branch)

### ISSUE THREAD

**Issue by likang1008-ctrl** [zeroclaw-labs/zeroclaw#2230]
### Summary

 Building with --features channel-lark fails on both the published crate and the latest main branch

### Affected component

channel

### Severity

S0 - data loss / security risk

### Current behavior

  Environment

  - OS: Windows 10/11 x86_64
  - Rust: stable (latest)
  - ZeroClaw: v0.1.7 (crates.io) and main branch (cf591719)

  Problem

  Building with --features channel-lark fails on both the published crate and the latest main branch.

  v0.1.7 (crates.io) errors

  cargo install zeroclaw --features whatsapp-web,channel-lark --force

  9 compilation errors in src/channels/lark.rs and src/channels/mod.rs:

  - cannot find value mention_only in this scope (lark.rs:343)
  - no field platform on type &LarkChannel (lark.rs:518, 372, 376, 380, 384)
  - mismatched types: expected LarkPlatform, found bool (lark.rs:365)
  - no function or associated item named from_lark_config (mod.rs:2917)
  - no function or associated item named from_feishu_config (mod.rs:2926)

  main branch errors

  cargo install --git https://github.com/zeroclaw-labs/zeroclaw zeroclaw --features whatsapp-web,channel-lark --force

  2 compilation errors in src/security/file_link_guard.rs:

  - use of unstable library feature windows_by_handle (line 20)
  - the trait bound u64: From<Option<u32>> is not satisfied (line 20)

  Steps to reproduce

  cargo install zeroclaw --features whatsapp-web,channel-lark --force

### Expected behavior

Build succeeds with Lark/Feishu channel support enabled.

  Note

  whatsapp-web feature compiles and works fine. Only channel-lark is broken.

### Steps to reproduce

```bash
cargo install zeroclaw --features whatsapp-web,channel-lark --force
```

### Impact

Bug Cannot use Lark/Feishu channel on Windows — compilation fails, blocking Feishu integration

### Logs / stack traces

```text

```

### ZeroClaw version

v0.1.7

### Rust version

rustc 1.93.1

### Operating system

windows10 

### Regression?

Unknown

### Pre-flight checks

- [x] I reproduced this on the latest main branch or latest release.
- [x] I redacted secrets/tokens from logs.
- [x] I removed personal identifiers and replaced identity-specific data with neutral placeholders.

**Comment by theonlyhennygod** [comment]
Revalidated this on current `main` and could not reproduce the reported compile break in `channel-lark`.

What I verified:
- `cargo check --features channel-lark` ✅
- `cargo check --features whatsapp-web,channel-lark` ✅
- `cargo test --no-default-features --features channel-lark lark_from_lark_config_ignores_legacy_feishu_flag -- --nocapture` ✅

Source check on `main`:
- `src/security/file_link_guard.rs` now uses stable Windows metadata APIs:
  - `use std::os::windows::fs::MetadataExt;`
  - `u64::from(metadata.number_of_links())`
- The previously reported `windows_by_handle` / `From<Option<u32>>` errors are not present in current source.

Environment caveat from this macOS host:
- `cargo check --features channel-lark --target x86_64-pc-windows-msvc` cannot be used here as definitive Windows proof because cross-target C dependencies require a Windows SDK/toolchain (`windows.h`/`assert.h`), which is not available in this environment.

Given the above, this issue appears resolved on `main`. If you can still reproduce on a native Windows checkout of latest `main`, please reopen with the exact commit SHA and full compiler output and we’ll continue immediately.

**Comment by likang1008-ctrl** [comment]
---
  Still getting the same error on Windows with latest main (commit a1d51b64):

  Compiling zeroclaw v0.1.7 (C:\Users\Administrator\.cargo\git\checkouts\zeroclaw-d47b3a8f1d261e9d\a1d51b6)
  error[E0658]: use of unstable library feature `windows_by_handle`
    --> src\security\file_link_guard.rs:20:24
     |
  20 |     u64::from(metadata.number_of_links())
     |                        ^^^^^^^^^^^^^^^

  error[E0277]: the trait bound `u64: std::convert::From<std::option::Option<u32>>` is not satisfied
    --> src\security\file_link_guard.rs:20:5
     |
  20 |     u64::from(metadata.number_of_links())
     |     ^^^

  Command used:
  cargo install --git https://github.com/zeroclaw-labs/zeroclaw zeroclaw --features whatsapp-web,channel-lark --force

  Environment:
  - OS: Windows 10/11 x86_64
  - Rust: stable (latest)
  - Commit: a1d51b64

  The src/security/file_link_guard.rs:20 still uses number_of_links() which is unstable on Windows.

  ---
