### ISSUE TITLE
[Bug]: cargo build --release --features channel-lark fails on v0.1.7 (and dev branch) — PR #1358 split broke LarkChannel

### ISSUE THREAD

**Issue by dianzuan** [zeroclaw-labs/zeroclaw#1991]
### Summary

`cargo build --release --features channel-lark` fails with 9 errors on both v0.1.7 and dev branch.

### Affected component

channel

### Severity

S1 - workflow blocked

## Root Cause
PR #1358 ("split lark and feishu providers") updated `src/channels/mod.rs` to call 
`LarkChannel::from_lark_config()` and `LarkChannel::from_feishu_config()`, and 
references `self.platform`, but `src/channels/lark.rs` still has the old struct 
without `platform` field and only exposes `from_config()`.

## Errors (truncated)
- `E0599: no function or associated item named "from_lark_config"`
- `E0599: no function or associated item named "from_feishu_config"` 
- `E0609: no field "platform" on type "&LarkChannel"` (×4)
- `E0308: mismatched types — expected "LarkPlatform", found "bool"`
- `E0425: cannot find value "mention_only" in this scope`

### Expected behavior

Successful compilation with Lark/Feishu channel support.

### Steps to reproduce

```bash
git checkout v0.1.7
cargo build --release --features channel-lark
```

### Impact

Affected users: Anyone trying to build ZeroClaw with Feishu/Lark channel support on v0.1.7 or dev branch
Frequency: always — 100% reproducible
Consequence: Cannot compile with --features channel-lark on v0.1.7 or dev. 
Workaround: v0.1.6 compiles successfully, but misses v0.1.7 features (prompt injection defense, Novita AI provider, etc.)

### Logs / stack traces

```text

```

### ZeroClaw version

v0.1.7

### Rust version

rustc 1.93.1

### Operating system

Ubuntu 24.04

### Regression?

Yes, it worked before

### Pre-flight checks

- [x] I reproduced this on the latest main branch or latest release.
- [x] I redacted secrets/tokens from logs.
- [x] I removed personal identifiers and replaced identity-specific data with neutral placeholders.

**Comment by theonlyhennygod** [comment]
Root cause confirmed: Lark/Feishu split wiring referenced constructor paths and platform-aware fields that were missing in `src/channels/lark.rs`, causing compile failures for channel-lark builds.

What changed:
- restored explicit `platform` state on `LarkChannel`
- fixed constructor wiring (`new` -> `new_with_platform`) so `mention_only` + platform are passed correctly
- added `LarkChannel::from_lark_config(...)` and `LarkChannel::from_feishu_config(...)` used by channel bootstrap

PR: https://github.com/zeroclaw-labs/zeroclaw/pull/1995

Validation:
- `cargo fmt --all -- --check` passes
- `cargo check --features channel-lark` still fails on existing unrelated mainline regressions outside this patch scope (approval manager/tooling/runtime API mismatches)

**Comment by theonlyhennygod** [comment]
Closing as resolved by upstream mainline fix in commit 7bea2b89 (`src/channels/lark.rs` now includes platform-aware constructors and `from_lark_config` / `from_feishu_config` wiring used by channels bootstrap).
